import { faker } from '@faker-js/faker'



const range = (len) => {
  const arr = []
  for (let i = 0; i < len; i++) {
    arr.push(i)
  }
  return arr
}

const newPerson = () => {
  return {
    userName: faker.person.fullName(),
    firstName: faker.person.firstName(),
    lastName: faker.person.lastName(),
    age: faker.number.int(40),
    visits: faker.number.int(1000),
    progress: faker.number.int(100),
    status: faker.helpers.shuffle([
      'relationship',
      'complicated',
      'single',
    ])[0],
  }
}

export function makeData(...lens) {
  const makeDataLevel = (depth = 0) => {
    const len = lens[depth]
    return range(len).map((d) => {
      return {
        ...newPerson(),
        subRows: lens[depth + 1] ? makeDataLevel(depth + 1) : undefined,
      }
    })
  }

  return makeDataLevel()
}


export function makeUsersData(...lens) {
  const makeDataLevel = (depth = 0) => {
    const len = lens[depth]
    return range(len).map((d) => {
      return {
        ...newPerson(),
        subRows: lens[depth + 1] ? makeDataLevel(depth + 1) : undefined,
      }
    })
  }

  return makeDataLevel()
}

export function makeDqRules() {
  return [
    {
        "id": 73,
        "ruleId": "C011",
        "ruleErrMsg": "Inceptiond date is null",
        "validFrom": "2019-12-10T00:00:00",
        "validTo": "2019-12-30T00:00:00",
        "active": true,
        "isTechRule": null,
        "isInstrRule": true,
        "isPrtctnRule": null,
        "isCtpyRule": null,
        "isRefIntegrityRule": null,
        "attrName": "Inception date",
        "cubeId": null,
        "ruleType": "COMPLETENESS",
        "applDataIl": null,
        "applBirdIl": true,
        "applBirdEil": null,
        "applRblAc": null,
        "applRblShs": null,
        "applDnbAc": null,
        "ruleCondition": "ince is null",
        "reasonForDeactivation": null
    },
    {
        "id": 14,
        "ruleId": "CT001",
        "ruleErrMsg": "CNTRPRTY_ID Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "CNTRPRTY_ID",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "CNTRPRTY_ID IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 15,
        "ruleId": "CT002",
        "ruleErrMsg": "DT_RFRNC Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "DT_RFRNC",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "DT_RFRNC IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 16,
        "ruleId": "CT003",
        "ruleErrMsg": "REPORT_AGNT_ID Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "REPORT_AGNT_ID",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "REPORT_AGNT_ID IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 17,
        "ruleId": "CT004",
        "ruleErrMsg": "OBSRVD_AGNT_ID Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "OBSRVD_AGNT_ID",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "OBSRVD_AGNT_ID IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 18,
        "ruleId": "CT005",
        "ruleErrMsg": "RUN_CONTEXT_ID Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "RUN_CONTEXT_ID",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "RUN_CONTEXT_ID IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 19,
        "ruleId": "CT006",
        "ruleErrMsg": "IL_SYSTEM_CD Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "IL_SYSTEM_CD",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "IL_SYSTEM_CD IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 20,
        "ruleId": "CT007",
        "ruleErrMsg": "FO_SYSTEM_CD Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "FO_SYSTEM_CD",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "FO_SYSTEM_CD IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 21,
        "ruleId": "CT008",
        "ruleErrMsg": "SRC_SYS_CD Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "SRC_SYS_CD",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "SRC_SYS_CD IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 22,
        "ruleId": "CT009",
        "ruleErrMsg": "BO_CD Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "BO_CD",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "BO_CD IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 23,
        "ruleId": "CT010",
        "ruleErrMsg": "FINANCE_DEPT_CD Can not be Empty when the country of residence of the counterparty is Netherlands\r\n\r\n",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "FINANCE_DEPT_CD",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "FINANCE_DEPT_CD IS NULL AND CNTRY = 'NL'",
        "reasonForDeactivation": ""
    },
    {
        "id": 24,
        "ruleId": "CT011",
        "ruleErrMsg": "PRSPCTV_ID Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "PRSPCTV_ID",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "PRSPCTV_ID IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 25,
        "ruleId": "CT012",
        "ruleErrMsg": "IMMDT_PRNT_UNDRT_ID_STRNG Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "IMMDT_PRNT_UNDRT_ID_STRNG",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "IMMDT_PRNT_UNDRT_ID_STRNG IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 26,
        "ruleId": "CT013",
        "ruleErrMsg": "ULTMT_PRNT_UNDRT_ID_STRNG Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "ULTMT_PRNT_UNDRT_ID_STRNG",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "ULTMT_PRNT_UNDRT_ID_STRNG IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 27,
        "ruleId": "CT014",
        "ruleErrMsg": "HD_OFFC_UNDRT_ID_STRNG Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "HD_OFFC_UNDRT_ID_STRNG",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "HD_OFFC_UNDRT_ID_STRNG IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 28,
        "ruleId": "CT015",
        "ruleErrMsg": "NTNL_ID Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "NTNL_ID",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "NTNL_ID IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 29,
        "ruleId": "CT016",
        "ruleErrMsg": "DT_DFLT_STTS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "DT_DFLT_STTS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "DT_DFLT_STTS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 30,
        "ruleId": "CT017",
        "ruleErrMsg": "ACCNTNG_FRMWRK_SL Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "ACCNTNG_FRMWRK_SL",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "ACCNTNG_FRMWRK_SL IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 31,
        "ruleId": "CT018",
        "ruleErrMsg": "EXCPTN_MRG_ACQSTN Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "EXCPTN_MRG_ACQSTN",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "EXCPTN_MRG_ACQSTN IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 32,
        "ruleId": "CT019",
        "ruleErrMsg": "EQTY Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "EQTY",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "EQTY IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 33,
        "ruleId": "CT020",
        "ruleErrMsg": "ENTRPRS_SZ_CHC Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "ENTRPRS_SZ_CHC",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "ENTRPRS_SZ_CHC IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 34,
        "ruleId": "CT021",
        "ruleErrMsg": "ENTRPRS_SZ Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "ENTRPRS_SZ",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "ENTRPRS_SZ IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 35,
        "ruleId": "CT022",
        "ruleErrMsg": "ECNMC_ACTVTY Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "ECNMC_ACTVTY",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "ECNMC_ACTVTY IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 36,
        "ruleId": "CT023",
        "ruleErrMsg": "DT_STTS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "DT_STTS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "DT_STTS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 37,
        "ruleId": "CT024",
        "ruleErrMsg": "INSTTTNL_SCTR Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "INSTTTNL_SCTR",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "INSTTTNL_SCTR IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 38,
        "ruleId": "CT025",
        "ruleErrMsg": "DT_ENTRPRS_SZ Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "DT_ENTRPRS_SZ",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "DT_ENTRPRS_SZ IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 39,
        "ruleId": "CT026",
        "ruleErrMsg": "INSTTTNL_SCTR_CNTRL Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "INSTTTNL_SCTR_CNTRL",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "INSTTTNL_SCTR_CNTRL IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 40,
        "ruleId": "CT027",
        "ruleErrMsg": "CTY Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "CTY",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "CTY IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 41,
        "ruleId": "CT028",
        "ruleErrMsg": "CRDT_QLTY_STTS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "CRDT_QLTY_STTS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "CRDT_QLTY_STTS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 42,
        "ruleId": "CT029",
        "ruleErrMsg": "CNTRY Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "CNTRY",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "CNTRY IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 43,
        "ruleId": "CT031",
        "ruleErrMsg": "CNTRL_PBLC_BDS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "CNTRL_PBLC_BDS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "CNTRL_PBLC_BDS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 44,
        "ruleId": "CT032",
        "ruleErrMsg": "CHRCTRSTCS_CRDT_RSK Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "CHRCTRSTCS_CRDT_RSK",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "CHRCTRSTCS_CRDT_RSK IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 45,
        "ruleId": "CT033",
        "ruleErrMsg": "BLNC_SHT_TTL Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "BLNC_SHT_TTL",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "BLNC_SHT_TTL IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 46,
        "ruleId": "CT034",
        "ruleErrMsg": "APPRCH_PRDNTL_PRPSS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "APPRCH_PRDNTL_PRPSS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "APPRCH_PRDNTL_PRPSS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 47,
        "ruleId": "CT035",
        "ruleErrMsg": "ANNL_TRNVR Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "ANNL_TRNVR",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "ANNL_TRNVR IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 48,
        "ruleId": "CT036",
        "ruleErrMsg": "DT_INTTN_LGL_PRCDNGS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "DT_INTTN_LGL_PRCDNGS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "DT_INTTN_LGL_PRCDNGS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 49,
        "ruleId": "CT037",
        "ruleErrMsg": "NM_ENTTY Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "NM_ENTTY",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "NM_ENTTY IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 50,
        "ruleId": "CT038",
        "ruleErrMsg": "TYP_ENTRPRS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "TYP_ENTRPRS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "TYP_ENTRPRS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 51,
        "ruleId": "CT039",
        "ruleErrMsg": "TT_ASST_INVST Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "TT_ASST_INVST",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "TT_ASST_INVST IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 52,
        "ruleId": "CT040",
        "ruleErrMsg": "TRRTRL_UNT Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "TRRTRL_UNT",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "TRRTRL_UNT IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 53,
        "ruleId": "CT041",
        "ruleErrMsg": "STTS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "STTS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "STTS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 54,
        "ruleId": "CT042",
        "ruleErrMsg": "STRT Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "STRT",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "STRT IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 55,
        "ruleId": "CT043",
        "ruleErrMsg": "PSTL_CD Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "PSTL_CD",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "PSTL_CD IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 56,
        "ruleId": "CT044",
        "ruleErrMsg": "PR_LSS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "PR_LSS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "PR_LSS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 57,
        "ruleId": "CT045",
        "ruleErrMsg": "PD Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "PD",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "PD IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 58,
        "ruleId": "CT046",
        "ruleErrMsg": "NMBR_EMPLYS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "NMBR_EMPLYS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "NMBR_EMPLYS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 59,
        "ruleId": "CT047",
        "ruleErrMsg": "LGL_PRCDNG_STTS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "LGL_PRCDNG_STTS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "LGL_PRCDNG_STTS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 60,
        "ruleId": "CT048",
        "ruleErrMsg": "LGL_FRM Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "LGL_FRM",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "LGL_FRM IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 61,
        "ruleId": "CT049",
        "ruleErrMsg": "LEI Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "LEI",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "LEI IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 62,
        "ruleId": "CT050",
        "ruleErrMsg": "IS_SM_PRTCTN_SCHM Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "IS_SM_PRTCTN_SCHM",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "IS_SM_PRTCTN_SCHM IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 63,
        "ruleId": "CT051",
        "ruleErrMsg": "IS_PLLNG_EFFCT Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "IS_PLLNG_EFFCT",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "IS_PLLNG_EFFCT IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 64,
        "ruleId": "CT052",
        "ruleErrMsg": "IS_LCL_GVRNMNT_TRTD_PS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "IS_LCL_GVRNMNT_TRTD_PS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "IS_LCL_GVRNMNT_TRTD_PS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 65,
        "ruleId": "CT053",
        "ruleErrMsg": "IS_CNTRL_GVRNMNT_TRTD_PS Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "IS_CNTRL_GVRNMNT_TRTD_PS",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "IS_CNTRL_GVRNMNT_TRTD_PS IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 66,
        "ruleId": "CT054",
        "ruleErrMsg": "IS_CNTRL_GVRNMNT_TRTD_LG Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "IS_CNTRL_GVRNMNT_TRTD_LG",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "IS_CNTRL_GVRNMNT_TRTD_LG IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 67,
        "ruleId": "CT055",
        "ruleErrMsg": "INTRNTNL_ORGNSTN_CD Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "INTRNTNL_ORGNSTN_CD",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "INTRNTNL_ORGNSTN_CD IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 68,
        "ruleId": "CT056",
        "ruleErrMsg": "TYP_CNTRPRTY_EXTRNL_ID Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "TYP_CNTRPRTY_EXTRNL_ID",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "TYP_CNTRPRTY_EXTRNL_ID IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 69,
        "ruleId": "CT057",
        "ruleErrMsg": "CNTRPRTY_EXTRNL_ID Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "CNTRPRTY_EXTRNL_ID",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": false,
        "applRblShs": false,
        "applDnbAc": false,
        "ruleCondition": "CNTRPRTY_EXTRNL_ID IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 70,
        "ruleId": "CT058",
        "ruleErrMsg": "PRSPCTV Can not be Empty",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "PRSPCTV",
        "cubeId": "IL_CTPY",
        "ruleType": "COMPLETENESS",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "PRSPCTV IS NULL",
        "reasonForDeactivation": ""
    },
    {
        "id": 71,
        "ruleId": "CT101",
        "ruleErrMsg": "Reported LGL_FRM does not belong to reported country",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "LGL_FRM",
        "cubeId": "IL_CTPY",
        "ruleType": "CONSISTENCY",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "substring (LGL_FRM,1,2) <> CNTRY",
        "reasonForDeactivation": ""
    },
    {
        "id": 72,
        "ruleId": "CT102",
        "ruleErrMsg": "LGL_PRCDNG_STTS and PD are not in line. A  counterparty with sttaus of legal proceeding as 'Bankruptcy / insolvency' can not have a Probability of default <>1",
        "validFrom": "2019-01-01T00:00:00",
        "validTo": "2099-01-01T00:00:00",
        "active": true,
        "isTechRule": false,
        "isInstrRule": false,
        "isPrtctnRule": false,
        "isCtpyRule": true,
        "isRefIntegrityRule": false,
        "attrName": "LGL_PRCDNG_STTS",
        "cubeId": "IL_CTPY",
        "ruleType": "REF_INTEGRITY",
        "applDataIl": true,
        "applBirdIl": true,
        "applBirdEil": true,
        "applRblAc": true,
        "applRblShs": false,
        "applDnbAc": true,
        "ruleCondition": "LGL_PRCDNG_STTS  = '3' and PD <> cast(1 as character)",
        "reasonForDeactivation": ""
    }
]
}
